name: Test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  repository_dispatch:
    types:
      - test
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        core-version:
          - 8.5.2
          - 8.5.12
          - 9.0.1
          - 9.1.3
          - 9.2.3
    name: Test (${{ matrix.core-version }})
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/concrete5-community/docker5:${{ matrix.core-version }}
      env:
        GITHUB_WORKSPACE: /app/packages/http_client_compat
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Move package
        run: mv -- "$GITHUB_WORKSPACE" /app/packages/ && mkdir -p -- "$GITHUB_WORKSPACE"
      -
        name: Start DB
        run: ccm-service start db
      -
        name: Install package
        run: cd /app && c5 c5:package:install http_client_compat
      -
        name: Test package
        run: cd /app && c5 c5:exec /app/packages/http_client_compat/.github/workflows/test.php
